mz.h: fix build with gcc 4.8
gcc 4.8 does not support __has_include directive as a result the build
will fail on:

/home/naourr/work/instance-1/output-1/build/minizip-2.10.0/mz.h:162:44: error: missing binary operator before token "("
    (defined(__has_include) && __has_include(<stdint.h>))
                                            ^

Fix it by appling:
https://gcc.gnu.org/onlinedocs/gcc-10.1.0/cpp/_005f_005fhas_005finclude.html

Fix #510

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>